apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    jsonData:
      httpMode: GET
    isDefault: true
    editable: true
